#ifndef XRPC_ERROR_H
#define XRPC_ERROR_H

/*
 * Every call returns 0 as success
 */

#define XRPC_SUCCESS 0

/*
 * RPC API Server errors
 *
 * From -1 to - 49
 */

#define XRPC_API_ERR_ALLOC -1
#define XRPC_API_ERR_HANDLER_ALREADY_REGISTERED -3
#define XRPC_API_ERR_INVALID_ARGS -5
#define XRPC_API_ERR_INVALID_TRANSPORT -6

/*
 * Protocol ERROR
 * From -50 to -99
 */

#define XRPC_PROTO_ERR_INVALID_DTYPE -50
#define XRPC_PROTO_ERR_SERIALIZATION_INVALID_ARGS -51
#define XRPC_PROTO_ERR_VERSION_MISMATCH -52
#define XRPC_PROTO_ERR_INVALID_OP -53

/*
 * Transport related errors. These can be return from connection oriented
 * transport backend. From -100 to -199
 */
#define XRPC_TRANSPORT_ERR_SOCKET -100
#define XRPC_TRANSPORT_ERR_BIND -101
#define XRPC_TRANSPORT_ERR_LISTEN -102
#define XRPC_TRANSPORT_ERR_ACCEPT -103
#define XRPC_TRANSPORT_ERR_CONN_CLOSED -104
#define XRPC_TRANSPORT_ERR_READ -105
#define XRPC_TRANSPORT_ERR_WRITE -106
#define XRPC_TRANSPORT_ERR_ADDRESS -107
#define XRPC_TRANSPORT_ERR_WOULD_BLOCK -109

/*
 * Internal errors. These are from ringbuffer, workers and other components not
 * exposed to the user
 *
 * From -200 to -299
 */
#define XRPC_INTERNAL_ERR_ALLOC -200
#define XRPC_INTERNAL_ERR_RINGBUF_FULL -201
#define XRPC_INTERNAL_ERR_RINGBUF_EMPTY -202
#define XRPC_INTERNAL_ERR_RINGBUF_INVALID_ARG -203
#define XRPC_INTERNAL_ERR_POOL_INVALID_ARG -204
#define XRPC_INTERNAL_ERR_POOL_FULL -205
#define XRPC_INTERNAL_ERR_POOL_EMPTY -206
#define XRPC_INTERNAL_ERR_INVALID_CONN -207

/*
 * Client errors
 * From -300 to -399
 */
#define XRPC_CLIENT_ERR_CONNECT -300
#define XRPC_CLIENT_ERR_INVALID_CONFIG -301
#define XRPC_CLIENT_ERR_INVALID_TRANSPORT -302
#define XRPC_CLIENT_ERR_NOT_CONNECTED -303
#define XRPC_CLIENT_ERR_PROTOCOL -304
#define XRPC_CLIENT_ERR_NOT_IMPLEMENTED -399
#endif // !XRPC_ERROR_H
